"""add complaint location

Revision ID: 14d4d47ccaec
Revises: 15d732a4a1d5
Create Date: 2026-09-01 23:55:03.138265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14d4d47ccaec'
down_revision: Union[str, Sequence[str], None] = '15d732a4a1d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('complaints', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'longitude')
    op.drop_column('complaints', 'latitude')
    # ### end Alembic commands ###
