"""add password reset otp fields

Revision ID: a6c006c05c18
Revises: 9dc3425e499b
Create Date: 2026-09-14 14:19:44.733256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6c006c05c18'
down_revision: Union[str, Sequence[str], None] = '9dc3425e499b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaint_attachments_complaint_id'), table_name='complaint_attachments')
    op.drop_index(op.f('ix_complaint_attachments_id'), table_name='complaint_attachments')
    op.drop_table('complaint_attachments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint_attachments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('complaint_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('storage_key', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('content_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('complaint_attachments_complaint_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('complaint_attachments_pkey'))
    )
    op.create_index(op.f('ix_complaint_attachments_id'), 'complaint_attachments', ['id'], unique=False)
    op.create_index(op.f('ix_complaint_attachments_complaint_id'), 'complaint_attachments', ['complaint_id'], unique=False)
    # ### end Alembic commands ###
