"""add password reset otp fields

Revision ID: f46ca8927dc8
Revises: f537c30dbaca
Create Date: 2026-09-14 14:25:25.095081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f46ca8927dc8'
down_revision: Union[str, Sequence[str], None] = 'f537c30dbaca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_reset_otp_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_reset_otp_expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('password_reset_otp_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('password_reset_otp_last_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reset_otp_last_sent_at')
    op.drop_column('users', 'password_reset_otp_attempts')
    op.drop_column('users', 'password_reset_otp_expires_at')
    op.drop_column('users', 'password_reset_otp_hash')
    # ### end Alembic commands ###
